# # A 3-Dimensional Stable Mixed Layer Example
#
# Here we simulate phytoplankton cells as Lagrangian particles in a 3D flow field generated by 
# [Oceananigans.jl](https://github.com/climate-machine/Oceananigans.jl).
# The domain is periodic in both directions horizontally and bounded in vertical direction.

#nb # %% {"slideshow": {"slide_type": "slide"}, "cell_type": "markdown"}
# ## 1. Import packages
#
using PlanktonIndividuals, Plots, JLD2

#nb # %% {"slideshow": {"slide_type": "slide"}, "cell_type": "markdown"}
# ## 2. Generate Flow Fields
#
# First we'll generate grid information
grid = gen_Grid(size=(32, 32, 64), spacing=(4, 4, 4))

# Then we use [Oceananigans.jl](https://github.com/climate-machine/Oceananigans.jl) to generate flow fields
# with a stable mixed layer. [Script used here]()


#nb # %% {"slideshow": {"slide_type": "slide"}, "cell_type": "markdown"}
# ## 3. Model Setup
#
# Next we setup the individual-based model by specifying the architecture, grid,
# number of individuals, parameters, and nutrient initial conditions.

model = PI_Model(CPUs(), grid; individual_size = (Nsp = 1, N = 2^7, cap = 8),
                 nut_source = [1.0, 0.02, 0.05, 0.01, 1.0, 0.1, 0.02, 0.2, 0.02, 0.001])

# We also need to setup a runtime simulation to run the model.
# The simulation includes time step, number of time steps, flow fields that
# will be used etc.

sim = PI_simulation(model, ΔT = 60, nΔT = 1, diag_freq = 3600, 
                    vels=(u=uvels, v=vvels, w=wvels))

#nb # %% {"slideshow": {"slide_type": "slide"}, "cell_type": "markdown"}
# ## 4. Run the Model
#
# Finaly, we run the model and plot the distribution of individuals as well as nutrient fields
# We use Plots.jl to plot individuals and a slice of nutrient fields.
#
function plot(model::PI_Model)
    ## Coordinate arrays for plotting
    xC, zC = collect(model.grid.xC)[3:34], collect(model.grid.zC)[3:66]

    ## a scatter plot embeded in the flow fields
    px = Array(model.individuals.phytos.sp1.data.x)
    pz = Array(model.individuals.phytos.sp1.data.z)
    p_plot = Plots.scatter(px, pz, xlims=(0,128), ylims=(-256,1), ms=5, color = :red, legend=:none)

    ## the middle slice of DOC field
    trac1 = Plots.contourf(xC, zC, Array(model.nutrients.DOC.data)[3:130,18,3:130]', xlabel="x (m)", ylabel="z (m)", clims=(0.5, 1.1), fmt=:png)

    ## Arrange the plots side-by-side.
    plt = Plots.plot(p_plot, trac1, size=(800, 400),
        title=[lpad(model.t÷86400,2,"0")*"day "*lpad(model.t÷3600-24*(model.t÷86400),2,"0")*"hour" "DOC (mmolC/L)"])

    return plt
end
#
# We run the model for 120 time steps (2 hour) and plot the individuals and DOC field.
for i in 1:120
    update!(sim)
end

plot(model)

#nb # %% {"slideshow": {"slide_type": "slide"}, "cell_type": "markdown"}
# Or you can use the following code to generate an animation like below
#
# ```
# anim = @animate for i in 1:120
#    update!(sim)
#    plot(model)
# end
# gif(anim, "anim_fps15.gif", fps = 15)
# ```
# ![animation](https://github.com/JuliaOcean/PlanktonIndividuals.jl/raw/master/examples/figures/anim_vertical_2D.gif)